name: Backend Deployment Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Ensure sshpass is available
      - name: Install sshpass
        run: |
          sudo apt-get update -y
          sudo apt-get install -y sshpass

      # 3️⃣ Prepare Bastion directory
      - name: Prepare Bastion Directory
        run: |
          echo "Preparing directory on Bastion..."
          sshpass -p "${{ secrets.BASTION_PASS }}" ssh -o StrictHostKeyChecking=no ec2-user@52.66.158.199 "
            sudo mkdir -p /tmp/backend-deploy &&
            sudo rm -rf /tmp/backend-deploy/* &&
            echo '/tmp/backend-deploy ready'
          "

      # 4️⃣ Copy backend repo files to Bastion
      - name: Copy Backend Files to Bastion
        run: |
          echo "Copying files to Bastion..."
          sshpass -p "${{ secrets.BASTION_PASS }}" scp -r -o StrictHostKeyChecking=no * ec2-user@52.66.158.199:/tmp/backend-deploy/

      # 5️⃣ Transfer from Bastion → Backend EC2
      - name: Copy Files from Bastion to Backend EC2
        run: |
          echo "Transferring files from Bastion to Backend EC2..."
          sshpass -p "${{ secrets.BASTION_PASS }}" ssh -o StrictHostKeyChecking=no ec2-user@52.66.158.199 "
            sshpass -p '${{ secrets.BACKEND_PASS }}' ssh -o StrictHostKeyChecking=no ec2-user@10.0.157.0 '
              sudo rm -rf /home/ec2-user/forteai-nexus-backend &&
              mkdir -p /home/ec2-user/forteai-nexus-backend
            ' &&
            sshpass -p '${{ secrets.BACKEND_PASS }}' scp -r -o StrictHostKeyChecking=no /tmp/backend-deploy/* ec2-user@10.0.157.0:/home/ec2-user/forteai-nexus-backend/
          "

      # 6️⃣ Create .env dynamically (no hardcoding)
      - name: Create Environment File on Backend
        run: |
          echo "Creating .env file dynamically..."
          sshpass -p "${{ secrets.BASTION_PASS }}" ssh -o StrictHostKeyChecking=no ec2-user@52.66.158.199 "
            sshpass -p '${{ secrets.BACKEND_PASS }}' ssh -o StrictHostKeyChecking=no ec2-user@10.0.157.0 '
              echo \"${{ secrets.BACKEND_ENV_FILE }}\" > /home/ec2-user/forteai-nexus-backend/.env
            '
          "

      # 7️⃣ Install dependencies and restart backend
      - name: Install Dependencies & Restart Backend
        run: |
          echo "Installing dependencies and restarting backend..."
          sshpass -p "${{ secrets.BASTION_PASS }}" ssh -o StrictHostKeyChecking=no ec2-user@52.66.158.199 "
            sshpass -p '${{ secrets.BACKEND_PASS }}' ssh -o StrictHostKeyChecking=no ec2-user@10.0.157.0 '
              cd /home/ec2-user/forteai-nexus-backend

              if ! command -v node >/dev/null 2>&1; then
                echo Installing Node.js...
                curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
                sudo yum install -y nodejs
              fi

              if ! command -v pm2 >/dev/null 2>&1; then
                echo Installing PM2...
                sudo npm install -g pm2
              fi

              npm install

              if pm2 list | grep -q forteai-backend; then
                pm2 restart forteai-backend
              else
                pm2 start server.js --name forteai-backend
              fi

              pm2 save
            '
          "
